services:
  application:
    build:
      context: .
      dockerfile: dockerfiles/php/Dockerfile
    image: mock_car_api
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app  
    entrypoint: ["sh", "./start.sh"]
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
    restart: always
    
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tennova_db
      MYSQL_USER: tennova_user
      MYSQL_PASSWORD: tennova_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_app

networks:
  laravel_app:
    driver: bridge

volumes:
  mysql_data:


