name: Deploy EC2

on:
  push:
    branches: [ api-dev ]

jobs:
  Deploy:
    name: JOBS
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_AWS_EC2_API_VEICULO }}
          HOSTNAME: ${{ secrets.URL_AWS_EC2_API_VEICULO }}
          USER_NAME: ${{ secrets.USER_AWS_EC2_UBUNTU }}
          
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
          cd /home/ubuntu/veiculos || exit 1

            echo '-> Pulling latest changes from GitHub...'
            git pull origin api-dev

            echo '-> Restarting Docker container...'
            sudo docker compose down
            sudo docker compose up -d --build
            "
